### ISSUE TITLE
can you give a json that i can use you plugins

### ISSUE THREAD

**Issue by Rigaln** [danielbrenom/MonsterLootHunter#1]
can you give a json that i can use you plugins

**Comment by danielbrenom** [comment]
Hello, sorry for the very late reply. I need to patch some things up with the code, but as soon as I do that, I'll put a release so you can use it as a developer plugin.

**Comment by danielbrenom** [comment]
Hello again, I've just finished updating and fixing the plugin. I released a first experiemental version. You can use it as a dev plugin, since I don't know hhow yet how to place it as a downloadable plugin inside Dalamud. I'll check how and make it work. Thanks.
