### ISSUE TITLE
Certain items with a Wiki page that list a category instead of the item itself are broken in the plugin.

### ISSUE THREAD

**Issue by OctaHeart** [danielbrenom/MonsterLootHunter#13]
Using Leather as an example, if you were to search for just "Leather" in MLH, it says it has no "Purchased from" or "Obtained From" Locations.

I assume that this is from the mod pulling from the page with the item name, and since https://ffxiv.consolegameswiki.com/wiki/Leather leads to any items that can be considered Leather instead of the Leather (Item) page, it returns with an error.

**Comment by danielbrenom** [comment]
Hello, thanks for the report. Indeed there's this issue with items which have desambiguations, I'll fix this for the ones I can find.

**Comment by danielbrenom** [comment]
Fixed on the new plugin version
