### ISSUE TITLE
is this being updates?

### ISSUE THREAD

**Issue by rboeglinjr2010** [danielbrenom/MonsterLootHunter#15]
love this plugin! Hopefully it comes back soon

**Comment by danielbrenom** [comment]
Hello, I've been away from the game for some time, but I'll try to update the plugin as soon as I can.

**Comment by danielbrenom** [comment]
As I'm not playing the game atm, the plugin will first be available for testing, if no issues are reported, it'll then go into general availability.

**Comment by rboeglinjr2010** [comment]
ok. i know 0 about coding but if you need a tester or anything i can help
with lmk. id even get you a 1 month sub if itll help

**Comment by danielbrenom** [comment]
@rboeglinjr2010 the plugin is already on the testing track, you can test/use it by opting-in for test builds on dalamud, if you haven't already. If you don't know how, the dalamud discord has info on how to opt-in.
I'll prob sent it to the main track in some days, if no problem is reported.

**Comment by danielbrenom** [comment]
The plugin is now on the stable track and available to everyone, I'll close this issue, if any there's any problem, feel free to open a new issue reporting it. Regards.
