### ISSUE TITLE
Cool idea, but where's the rest?

### ISSUE THREAD

**Issue by Astral-Crescent** [danielbrenom/MonsterLootHunter#3]
There is so much missing from this, it's useless to me as a Tailor... Feels like a massive oversight and shame.

**Comment by danielbrenom** [comment]
Hi, so this plugin is meant to show you location for drops from mobs or things you can buy from NPCs. Crafted/gathered items aren't the focus. There's some mats that indeed do not show where it drops, but I'm working on adding it.
For the crafted/gathered ones, I can add where they could come from, but again, that's not the focus for this plugin.

**Comment by danielbrenom** [comment]
For crafter stuff there's the plugin Allagan Tools, where you check recipes etc. For gatherer stuff there's GatherBuddy. I won't be integrating what they do. I can only show you quick information about those.

**Comment by danielbrenom** [comment]
This is going to be addressed as soon as version 1.0.8 is shipped on dalamud plugins. Hope it helps.
