### ISSUE TITLE
Cant Loot search drops from Crafting Log

### ISSUE THREAD

**Issue by LeAlmond** [danielbrenom/MonsterLootHunter#4]
Alright so not sure if this is an oversight or intentional (either way the work you've done so far is great).
I can loot search if I already have the item, but if I open my crafting log find an item I want the for example raptor leather, it needs raptor skins and alumen, so I right click on the leather but there's no option. 
Also thank you so much for this addon because its exactly what i've been looking for since I started playing.

**Comment by danielbrenom** [comment]
Hello, good to know that it's helping you.
About your situation, at the moment, the context menu integration I have coded is only working for the inventory menu. I plan on adding it to these other menus like crafting log etc. Don't worry, as soon as I get it ok it'll be released in an update.
As a workaround, you can use the slash command followed by the name of the mat and it'll open with the list filtered. It's not like the loot search that opens directly on the item, but it's close.
Thanks for using my plugin and hang in there, it'll come :)

**Comment by danielbrenom** [comment]
Hello, this is going to be addressed as soon as 1.0.9 is shipped on Dalamud. Thanks for your patience!

**Comment by LeAlmond** [comment]
awesome looking forward to being able to use it
